language: android
jdk:
#    - oraclejdk7
    - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
  license:
    - 'ConstraintLayout.*'
before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=$JAVA8_HOME

sudo: required

addons:
  sonarqube:
    branches:
        - master
        - develop
    token:
      secure: "CVvb6nAOdT3M/xNg3G1dr3ISW4tFRYNGhSYVH3JMicKpiWnrjlE5a9gDd0XJK7HRvEYb4XINerUlL739pmdsKHpWoRNwIMxfMl4qWpfdGG42/3nCyrdmbqQcUqrRLwK/Z8rg85HFCvgxEXLygUAxQYs6zt/Hm7sEo49e4dTSQ7ifSoZTl7Td2UCO4AxqK9TA4CBYNp4A2ZXYMZK4PmHY6tr3TiT2Sc8JSOgY0agCD9RMd1QkOMNECdlSTO7TRPyhIQkUDKq9OytHyKISoXgWxOSN5O+p7sqDOVfjyoxhExaNPzjvq0eXkAMrJ7LsxbEy1QGqhgJNLE9SEk6/032ogwH1bGwLHd6IlNj8Bn5RmZtQRq/+aT5UIgzWloMVr41MF298X4d4Jo30wH6vj5ImGKmjWC6dVZX95KdxqiWpYaZJvw34btqMUvz2b2p/OAgce6LwQ8ZB5/exVM+SaM6at7ugtyAikSdt+Qe0vQMIleGJ5+A+TaOl9IQ8KgcnZ4FOfH7fhwy6uFqp369Org7t0qj9/t/3RS0tnxrUOZtez5pPa1qu7Y+RPeLOFtoOsqzobngb/Y3FcprAfDCE2fFPoAVvgi/1iJFpEuz6YDTxbakI8At5MKozG3mAChuUbFQRGwk595cQpJtzhJCZ9gVfsf89u/WFHsATv3TCUBxLf/A="

script:
    - pwd
    - sonar-scanner
    - ./gradlew clean assemble check
after_success:
    - ./gradlew coveralls